APPLICATION = game_of_life

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..

# Modules and packages:
USEPKG += u8g2

USEMODULE += xtimer
USEMODULE += random
USEMODULE += u8g2_utf8

include $(RIOTBASE)/Makefile.include
